name: Docker Build

on:
  push:
    branches: [main]
    paths: 
      - '.dockerignore'
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    paths: 
      - '.dockerignore'
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'

permissions: {}

jobs:
  DockerBuild:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Docker Build
        run: docker build -t action-swiftlint .

      - name: Exit Status on Errors
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "2" ]]
        working-directory: ./test/errors
        shell: bash

      - name: Exit Status on No lintable files
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "1" ]]
        working-directory: ./test/no-lintable-files
        shell: bash

      - name: Exit Status on Warnings
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "0" ]]
        working-directory: ./test/Warnings
        shell: bash

      - name: Exit Status on Warnings with `--strict`
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint --strict &>/dev/null; echo $?)
          [[ $STATUS == "2" ]]
        working-directory: ./test/Warnings
        shell: bash

      - name: Output on Errors
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint|sort) expected.txt
        working-directory: ./test/errors
        shell: bash

      - name: Output on Warnings
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint|sort) expected.txt
        working-directory: ./test/Warnings
        shell: bash

      - name: Output on Warnings with WORKING_DIRECTORY environment variable
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm --env WORKING_DIRECTORY=Warnings action-swiftlint|sort) <(cat Warnings/expected.txt | sed -E 's/^(.*)file=(.*),(.*)/\1file=Warnings\/\2,\3/')
        working-directory: ./test
        shell: bash
